[programs.localnet]
mymoneydapp = "3ypkSbbEJjpVMDomEPyYLQoqJQS65PT17UKWgKPUdC7P"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/jjtom/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 test/"
